services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Custom Nginx config
    ports:
      - "5433:5433"  # Nginx for database
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: retrocode
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backEnd
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - app_network

  frontend:
    build: ./frontEnd
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge  # Define the network driver (optional)
